// src/routes/review/book/+page.svelte
<script lang="ts">
	import TextField from '$lib/TextField.svelte';
	import { base } from '$app/paths';
	import { writable } from 'svelte/store';

	type Book = {
		title: string;
		pubDate: string;
		pubPerson: string;
		pubPlace: string;
		logo: string;
		bookmaking: string;
		chefEditor: string;
		note: string;
	};

	const initBookData = () => {
		return {
			title: '',
			pubDate: '',
			pubPerson: '',
			pubPlace: '',
			logo: '',
			bookmaking: '',
			chefEditor: '',
			note: ''
		};
	};

	const book = writable(initBookData());
	let tsv: string;

	book.subscribe((b) => {
		tsv =
			b.title +
			'\t' +
			b.pubDate +
			'\t' +
			b.pubPerson +
			'\t' +
			b.pubPlace +
			'\t' +
			b.logo +
			'\t' +
			b.bookmaking +
			'\t' +
			b.chefEditor +
			'\t' +
			b.note;
	});

	const copy = () => {
		navigator.clipboard.writeText(tsv);
	};
</script>

<div class="text-sm breadcrumbs">
	<ul>
		<li><a href={`${base}/`}>げんしけん</a></li>
		<li><a href={`${base}/review/`}>レビュー班</a></li>
		<li><a href={`${base}/review/book`}>冊子</a></li>
	</ul>
</div>
<TextField label="タイトル" bind:value={$book.title} inputType="text" required />
<TextField label="発行日" bind:value={$book.pubDate} inputType="date" required />
<TextField label="発行者" bind:value={$book.pubPerson} inputType="text" required />
<TextField label="発行所" bind:value={$book.pubPlace} inputType="text" required />
<TextField label="表紙ロゴ" bind:value={$book.logo} inputType="text" required />
<TextField label="製本" bind:value={$book.bookmaking} inputType="text" required />
<TextField label="編集長" bind:value={$book.chefEditor} inputType="text" required />
<TextField label="備考" bind:value={$book.note} inputType="textarea" required />
<button class="btn btn-primary" on:click={copy}>copy</button>
<button class="btn btn-warning">clear</button>

// src/components/Book.vue
<template>
  <h2>冊子</h2>
  <div>
    <label for="book--title">タイトル</label>
    <input v-model="book.title" placeholder="タイトル" />
  </div>
  <div>
    <label for="book--pubdate">発行日</label>
    <input id="book--pubdate" type="date" v-model="book.pubdate" />
  </div>
  <div>
    <label for="book--publisher">発行者</label>
    <input id="book--publisher" type="text" v-model="book.publisher" />
  </div>
  <div>
    <label for="book--publisher">発行所</label>
    <input id="book--publisher" type="text" v-model="book.pubplace" />
  </div>
  <div>
    <label for="book--logo">表紙ロゴ</label>
    <input id="book--logo" type="text" v-model="book.logo" />
  </div>
  <div>
    <label for="book--bookmaking">製本</label>
    <input id="book--bookmaking" type="text" v-model="book.bookmaking" />
  </div>
  <div>
    <label for="book--edit-chef">編集長</label>
    <input id="book--edit-chef" type="text" v-model="book.editChef" />
  </div>
  <div>
    <label for="book--edit-chef">備考</label>
    <textarea v-model="book.note" placeholder="add multiple lines"></textarea>
  </div>
  <div>
    <code>{{tsv}}</code>
  </div>
  <button @click="copyTSV(tsv.value)">copy</button>
</template>

<script lang="ts">
import { watchEffect , ref, reactive, computed, defineComponent } from 'vue'

type Book = {
  title: string
  pubdate: string
  publisher: string
  pubplace: string
  logo: string
  bookmaking: string
  editChef: string
  note: string
}

export default defineComponent({
  setup() {
    const tsv = ref("");
    const book: Book = reactive({
      title: '',
      pubdate: '',
      publisher: '',
      pubplace: '',
      logo: '',
      bookmaking: '',
      editChef: '',
      note: ''
    });
    watchEffect(() => {
      tsv.value = (
        book.title +
        '\t' +
        book.pubdate +
        '\t' +
        book.publisher +
        '\t' +
        book.pubplace +
        '\t' +
        book.logo +
        '\t' +
        book.bookmaking +
        '\t' +
        book.editChef +
        '\t' +
        book.note +
        '\t'
      );
      //console.log(tsv);
    });
    function copyTSV() {
      navigator.clipboard.writeText(tsv.value)
    };
    return {
      book,
      tsv,
      copyTSV,
    }
  }
})

</script>
